/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BsinButton {
        "look": string;
        "primary": boolean;
    }
    interface BsinModal {
        "open": boolean;
        "title": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBsinButtonElement extends Components.BsinButton, HTMLStencilElement {
    }
    var HTMLBsinButtonElement: {
        prototype: HTMLBsinButtonElement;
        new (): HTMLBsinButtonElement;
    };
    interface HTMLBsinModalElement extends Components.BsinModal, HTMLStencilElement {
    }
    var HTMLBsinModalElement: {
        prototype: HTMLBsinModalElement;
        new (): HTMLBsinModalElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bsin-button": HTMLBsinButtonElement;
        "bsin-modal": HTMLBsinModalElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BsinButton {
        "look"?: string;
        "primary"?: boolean;
    }
    interface BsinModal {
        "open"?: boolean;
        "title"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "bsin-button": BsinButton;
        "bsin-modal": BsinModal;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bsin-button": LocalJSX.BsinButton & JSXBase.HTMLAttributes<HTMLBsinButtonElement>;
            "bsin-modal": LocalJSX.BsinModal & JSXBase.HTMLAttributes<HTMLBsinModalElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
